### ISSUE TITLE
Cannot find module "eyes"

### ISSUE THREAD

**Issue by Asmor** [iostreamer-X/Awkward#1]
Just installed this via npm and tried running ps(). It complained about missing module "eyes"

```
itoltz@awk ward:~$ ps()

/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:75
    throw e;
          ^
Error: Cannot find module 'eyes'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/opt/node/lib/node_modules/awkward/util.coffee:2:18)
  at Object.<anonymous> (/opt/node/lib/node_modules/awkward/util.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/opt/node/lib/node_modules/awkward/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/opt/node/lib/node_modules/awkward/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/opt/node/lib/node_modules/awkward/terminal/structure.coffee:1:9)
  at Object.<anonymous> (/opt/node/lib/node_modules/awkward/terminal/structure.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/opt/node/lib/node_modules/awkward/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/opt/node/lib/node_modules/awkward/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/opt/node/lib/node_modules/awkward/terminal/core.coffee:3:17)
  at Object.<anonymous> (/opt/node/lib/node_modules/awkward/terminal/core.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/opt/node/lib/node_modules/awkward/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/opt/node/lib/node_modules/awkward/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at module.exports (/opt/node/lib/node_modules/awkward/terminal/handler.coffee:15:4)
  at CommandInstance.handler_action (/opt/node/lib/node_modules/awkward/terminal/main.coffee:2:3)
  at EventEmitter.session.execCommandSet (/opt/node/lib/node_modules/awkward/node_modules/vorpal/dist/session.js:470:20)
  at EventEmitter.vorpal._exec (/opt/node/lib/node_modules/awkward/node_modules/vorpal/dist/vorpal.js:959:18)
  at EventEmitter.vorpal._execQueueItem (/opt/node/lib/node_modules/awkward/node_modules/vorpal/dist/vorpal.js:750:17)
  at EventEmitter.vorpal._queueHandler (/opt/node/lib/node_modules/awkward/node_modules/vorpal/dist/vorpal.js:734:10)
  at EventEmitter.vorpal.exec (/opt/node/lib/node_modules/awkward/node_modules/vorpal/dist/vorpal.js:681:10)
  at /opt/node/lib/node_modules/awkward/node_modules/vorpal/dist/vorpal.js:624:10
  at [object Object].completed (/opt/node/lib/node_modules/awkward/node_modules/vorpal/dist/ui.js:215:13)
  at [object Object].PromptUI.onCompletion (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/lib/ui/prompt.js:57:10)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1550:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1489:14)
  at Subject.Rx.Subject.addProperties.onCompleted (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5871:19)
  at Subject.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.completed (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5796:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1489:14)
  at AutoDetachObserver.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.completed (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5796:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1489:14)
  at InnerObserver.onCompleted (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:2966:65)
  at InnerObserver.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.completed (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5796:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1489:14)
  at AutoDetachObserver.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.completed (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5796:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1489:14)
  at InnerObserver.onCompleted (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:2966:65)
  at InnerObserver.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.completed (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5796:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1489:14)
  at AutoDetachObserver.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.completed (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5796:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1489:14)
  at /opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/lib/utils/utils.js:18:13
  at f (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/run-async/node_modules/once/once.js:17:25)
  at /opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/lib/ui/prompt.js:86:7
  at module.exports (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/run-async/index.js:23:5)
  at Prompt.filter (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/lib/prompts/base.js:128:3)
  at Prompt.<anonymous> (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/lib/prompts/base.js:56:10)
  at Prompt.<anonymous> (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/lib/prompts/input.js:98:10)
  at module.exports (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/run-async/index.js:23:5)
  at Prompt.filter (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/lib/prompts/base.js:128:3)
  at Prompt.onEnd (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/lib/prompts/input.js:90:8)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1535:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)
  at AnonymousObserver.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.next (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5782:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)
  at AnonymousObserver._onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:4234:13)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1535:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)
  at AnonymousObserver.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.next (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5782:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)
  at InnerObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:4306:29)
  at InnerObserver.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.next (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5782:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)
  at Subject.Rx.Subject.addProperties.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5902:19)
  at Subject.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.next (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5782:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)
  at AutoDetachObserver.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.next (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5782:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)
  at InnerObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:3167:90)
  at InnerObserver.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.next (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5782:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)
  at /opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/lib/prompts/base.js:96:18
  at module.exports (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/run-async/index.js:23:5)
  at AnonymousObservable.__subscribe (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/lib/prompts/base.js:95:7)
  at AnonymousObservable.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at [object Object].setDisposable [as action] (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5741:44)
  at [object Object].ScheduledItem.invokeCore (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:821:17)
  at [object Object].ScheduledItem.invoke (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:809:40)
  at runTrampoline (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1096:37)
  at tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at Scheduler.scheduleNow [as _schedule] (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1106:45)
  at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:862:19)
  at AnonymousObservable.innerSubscribe [as _subscribe] (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5753:32)
  at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1604:19)
  at MergeAllObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:3136:37)
  at MergeAllObserver.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.next (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5782:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)
  at InnerObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1790:16)
  at InnerObserver.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.next (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5782:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)
  at InnerObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:4056:14)
  at InnerObserver.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.next (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5782:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)
  at Subject.Rx.Subject.addProperties.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5902:19)
  at Subject.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.next (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5782:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)
  at AutoDetachObserver.tryCatcher (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
  at AutoDetachObserverPrototype.next (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5782:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)
  at Interface.innerHandler (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:4534:11)
  at Interface.emit (events.js:95:17)
  at Interface._onLine (readline.js:202:10)
  at Interface._line (readline.js:531:8)
  at Interface._ttyWrite (readline.js:760:14)
  at Interface.rl._ttyWrite (/opt/node/lib/node_modules/awkward/node_modules/vorpal/node_modules/inquirer/node_modules/readline2/index.js:105:15)
  at ReadStream.onkeypress (readline.js:99:10)
  at ReadStream.emit (events.js:117:20)
  at emitKey (readline.js:1095:12)
  at ReadStream.onData (readline.js:840:14)
  at ReadStream.emit (events.js:95:17)
  at ReadStream.<anonymous> (_stream_readable.js:748:14)
  at ReadStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:410:10)
  at emitReadable (_stream_readable.js:406:5)
  at readableAddChunk (_stream_readable.js:168:9)
  at ReadStream.Readable.push (_stream_readable.js:130:10)
  at TTY.onread (net.js:528:21)

```

**Comment by iostreamer-X** [comment]
I added 'eyes' as a direct dependency and have published the changes on npm, the latest version is 1.0.3. I think reinstalling the app would make it work.

**Comment by Asmor** [comment]
Updated and no longer getting this issue.

**Comment by iostreamer-X** [comment]
Awesome!
